// packages/arcodesign-vue/components/cell/Cell.vue
<script lang="ts" setup>
import { inject } from 'vue';
import { getPrefixCls } from '../context-provider';
import { CellEmits, CellProps } from './type';
import { cellGroupInjectionKey } from './utils';
import Arrow from './Arrow.vue';

const props = withDefaults(defineProps<CellProps>(), {
    bordered: true,
});
const emit = defineEmits<CellEmits>();
const prefix = getPrefixCls('cell');
const groupContext = inject(cellGroupInjectionKey, { isFromGroup: false });

function handleClick(e: Event) {
    emit('click', e);
}
</script>

<template>
    <div
        :class="[
            prefix,
            'all-border-box',
            { 'without-group': !groupContext.isFromGroup, 'bordered': props.bordered }
        ]"
        @click="handleClick"
    >
        <slot name="prepend"></slot>
        <div :class="[`${prefix}-inner`, { 'has-desc': $slots.desc }]">
            <div v-if="$slots.icon" :class="`${prefix}-label-icon`">
                <slot name="icon"></slot>
            </div>
            <div v-if="$slots.label || $slots.desc" :class="`${prefix}-label`">
                <div :class="`${prefix}-title`">
                    <slot name="label"></slot>
                </div>
                <div v-if="$slots.desc" :class="`${prefix}-desc`">
                    <slot name="desc"></slot>
                </div>
            </div>
            <div :class="[`${prefix}-content`, { 'has-label': $slots.label || $slots.desc }]">
                <div v-if="props.text" :class="`${prefix}-text`">
                    {{ props.text }}
                </div>
                <slot></slot>
            </div>
            <div v-if="props.showArrow" :class="`${prefix}-arrow-icon`">
                <slot name="arrow">
                    <Arrow />
                </slot>
            </div>
        </div>
        <slot name="append"></slot>
    </div>
  </template>

// packages/arcodesign/components/cell/cell.tsx
import React, { useRef, forwardRef, Ref, useImperativeHandle } from 'react';
import { cls } from '@arco-design/mobile-utils';
import { ContextLayout } from '../context-provider';
import Arrow from './arrow';
import { GroupContext } from './group';
import { CellProps, CellRef } from './type';

export const Cell = forwardRef((props: CellProps, ref: Ref<CellRef>) => {
    const {
        className = '',
        style,
        icon,
        label,
        desc,
        text,
        children,
        showArrow,
        arrow,
        prepend,
        append,
        bordered = true,
        onClick,
    } = props;
    const domRef = useRef<HTMLDivElement | null>(null);

    useImperativeHandle(ref, () => ({
        dom: domRef.current,
    }));

    return (
        <ContextLayout>
            {({ prefixCls }) => (
                <GroupContext.Consumer>
                    {({ isFromGroup }) => (
                        <div
                            className={cls(
                                `${prefixCls}-cell`,
                                'all-border-box',
                                { 'without-group': !isFromGroup },
                                { bordered },
                                className,
                            )}
                            style={style}
                            ref={domRef}
                            onClick={e => onClick && onClick(e)}
                        >
                            {prepend}
                            <div className={cls(`${prefixCls}-cell-inner`, { 'has-desc': desc })}>
                                {icon ? <div className="cell-label-icon">{icon}</div> : null}
                                {label || desc ? (
                                    <div className="cell-label">
                                        <div className="cell-title">{label}</div>
                                        {desc ? <div className="cell-desc">{desc}</div> : null}
                                    </div>
                                ) : null}
                                <div className={`cell-content ${label || desc ? 'has-label' : ''}`}>
                                    {text ? <div className="cell-text">{text}</div> : null}
                                    {children}
                                </div>
                                {showArrow ? (
                                    <div className="cell-arrow-icon">{arrow || <Arrow />}</div>
                                ) : null}
                            </div>
                            {append}
                        </div>
                    )}
                </GroupContext.Consumer>
            )}
        </ContextLayout>
    );
});
