// sites/mobile-vue/components/Demo.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import Arrow from './Arrow.vue';
import { useRouter } from 'vue-router';

const props = defineProps(['name', 'doc']);
const router = useRouter();
const Component = props.doc;

onMounted(() => {
    window.scrollTo(0, 0);
});
</script>
<template>
    <div class="arcodesign-mobile-demo-wrapper">
        <div className="demo-content" :id="`demo-${name}`">
            <div
                class="arrow-back"
                @click="router.back()"
            >
                <Arrow class="arrow-back-icon" />
            </div>
            <Component />
        </div>
    </div>
</template>

// sites/mobile/widgets/demo.tsx
import React, { useEffect } from 'react';
import IconArrowBack from '../../../packages/arcodesign/components/icon/IconArrowBack';
import getUrlParam from '../../utils/getUrlParam';

export interface IDemoProps {
    name: string;
    doc: any;
}

export default function Demo(props: IDemoProps) {
    const { name, doc } = props;
    const isFromWeb = Boolean(getUrlParam('from_web'));
    const hideBack = +getUrlParam('hide_back');

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    useEffect(() => {
        return () => {
            if (window.modalInstance && window.modalInstance.close) {
                window.modalInstance.close();
                window.modalInstance = null;
            }
        };
    }, [name]);

    return (
        <div className="arcodesign-mobile-demo-wrapper">
            {isFromWeb ? <div className="status-bar" /> : null}
            <div className="demo-content" id={`demo-${name}`}>
                {!hideBack ? (
                    <div
                        className="arrow-back"
                        onClick={() => history.back()}
                        style={{
                            top: isFromWeb ? '20px' : 0,
                        }}
                    >
                        <IconArrowBack />
                    </div>
                ) : null}
                {doc}
            </div>
        </div>
    );
}
