// sites/mobile-vue/components/Home.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue';
import { useRouter } from 'vue-router';
import { getMenuOrder } from '../../utils/menu';
import routes from '../pages/components/route';
import enRoutes from '../pages/components/route-en-US';
import { LanguageSupport } from '../../utils/language';
import Arrow from './Arrow.vue';

const props = defineProps(['language']);
const actualRoutes = computed(() => getMenuOrder(props.language === LanguageSupport.EN ? enRoutes : routes));
const router = useRouter();
const storageItemKey = 'vue_home_scroll';

onMounted(() => {
    document.body.classList.add('white-body');
    const scrollInfo = window.localStorage.getItem(storageItemKey) || '';
    const scrollTop = Number(scrollInfo.split('__')[1]) || 0;
    if (scrollTop) {
        window.scrollTo(0, scrollTop);
        window.localStorage.removeItem(storageItemKey);
    }
});

onUnmounted(() => {
    document.body.classList.remove('white-body');
});

function handleSubItemClick(route, type = 'components') {
    window.localStorage.setItem(storageItemKey, `${route}__${window.pageYOffset}`);
    window.parent.postMessage(
        {
            type,
            data: route,
            language: props.language,
        },
        '*',
    );
    router.push(`${props.language === LanguageSupport.EN ? '/en-US' : ''}/${type}/${route}`);
}
</script>

<template>
    <div class="arcodesign-mobile-home-wrapper">
        <div class="arcodesign-demo-logo">
            <img src="../assets/arco-logo.svg" class="logo" alt="Arco logo" />
        </div>
        <div v-for="(type, menuIndex) in Object.keys(actualRoutes)" :key="menuIndex" class="arcodesign-demo-menu">
            <div class="menu-wrap-title">{{ type }}</div>
            <div class="menu-item-wrap">
                <div
                    v-for="(route, index) in actualRoutes[type]"
                    :key="index"
                    class="menu-item"
                    @click="handleSubItemClick(route.key)"
                >
                    {{ route.name }}
                    <Arrow class="arrow" />
                </div>
            </div>
        </div>
    </div>
</template>

<style lang="less" scoped>
@import '../../../packages/arcodesign-vue/style/mixin.less';

.arcodesign-demo-logo {
    .rem(padding, 52, 16, 40);
    img {
        .rem(width, 200);
        .rem(height, 70);
    }
}

.arcodesign-demo-menu {
    .rem(padding, 0, 16, 28);
    .use-var(color, font-color);
    .menu-wrap-title {
        .rem(font-size, 14);
        .rem(line-height, 20);
        .rem(margin-bottom, 12);
        .rem(padding-left, 16);
        position: relative;
        color: #939aa3;
        &::before {
            content: " ";
            display: inline-block;
            width: 2px;
            .rem(height, 12);
            border-radius: 2px;
            .use-var(background, primary-color);
            .rem(margin, 0, 6, 0, 8);
            position: absolute;
            left: 0;
            top: 50%;
            transform: translateY(-50%);
        }
    }
    .menu-item {
        .rem(padding, 12, 16);
        .rem(font-size, 16);
        .rem(line-height, 22);
        position: relative;
        .use-var(background, card-background-color);
        cursor: pointer;
        .rem(border-radius, 8);
        &:not(:last-child) {
            .rem(margin-bottom, 8);
        }
        .arrow {
            position: absolute;
            .rem(right, 12);
            top: 50%;
            transform: translateY(-50%);
            color: #c9cdd4;
        }
    }
}
</style>

// sites/mobile/widgets/home.tsx
import React, { useContext, useEffect, useMemo } from 'react';
import routes from '../../pages/route';
import enRoutes from '../../pages/route-en-US';
import { HistoryContext } from '../entry';
import getUrlParam from '../../utils/getUrlParam';
import { LanguageSupport } from '../../utils/language';
import { getMenuOrder } from '../../utils/menu';

export function Arrow() {
    return (
        <svg className="arrow" width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M4.59486 2.2417C4.3996 2.43696 4.3996 2.75354 4.59486 2.94881L9.59905 7.95299L4.63604 12.916C4.44078 13.1113 4.44078 13.4278 4.63604 13.6231L4.98959 13.9767C5.18485 14.1719 5.50144 14.1719 5.6967 13.9767L11.3536 8.31981C11.5296 8.14376 11.5469 7.8691 11.4055 7.67364C11.3822 7.62725 11.3511 7.58374 11.3124 7.545L5.65552 1.88815C5.46026 1.69288 5.14367 1.69288 4.94841 1.88815L4.59486 2.2417Z"
                fill="currentColor"
            />
        </svg>
    );
}
interface IHomeProps {
    language?: LanguageSupport;
}
export default function Home({ language = LanguageSupport.CH }: IHomeProps) {
    const history = useContext(HistoryContext);
    const actualRoutes = useMemo(() => {
        const langRoutes = language === LanguageSupport.EN ? enRoutes : routes;
        return getMenuOrder(langRoutes, language);
    }, [routes, enRoutes, language]);
    /** 区分iframe通信 */
    const needJump = getUrlParam('need_jump') !== '0';

    useEffect(() => {
        document.body.classList.add('white-body');
        const scrollInfo = window.localStorage.getItem('home_scroll') || '';
        const scrollTop = Number(scrollInfo.split('__')[1]) || 0;
        if (scrollTop) {
            window.scrollTo(0, scrollTop);
            window.localStorage.removeItem('home_scroll');
        }
        return () => {
            document.body.classList.remove('white-body');
        };
    }, []);

    function handleSubItemClick(route) {
        window.localStorage.setItem('home_scroll', `${route}__${window.pageYOffset}`);
        window.parent.postMessage(
            {
                type: 'component',
                data: route,
                language,
            },
            '*',
        );
        if (needJump) {
            history.push(`${language === LanguageSupport.EN ? '/en-US' : ''}/components/${route}`);
        }
    }

    return (
        <div className="arcodesign-mobile-home-wrapper">
            <div className="arcodesign-demo-logo">
                <img
                    src="https://sf1-cdn-tos.toutiaostatic.com/obj/arco-mobile/_static_/arco-mobile-home-logo.png"
                    alt=""
                />
            </div>
            {Object.keys(actualRoutes).map((type, menuIndex) => (
                <div className="arcodesign-demo-menu" key={menuIndex}>
                    <div className="menu-wrap-title">{type}</div>
                    <div className="menu-item-wrap">
                        {actualRoutes[type].map((route, index) => (
                            <div
                                className="menu-item"
                                key={index}
                                onClick={() => handleSubItemClick(route.key)}
                            >
                                {route.name}
                                <Arrow />
                            </div>
                        ))}
                    </div>
                </div>
            ))}
        </div>
    );
}
